version: '3.8'
name: development
services:
  eu-tours:
    container_name: eu-tours
    image: anicmarko9/eu-tours:1.0
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - dev
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: on-failure
    ports:
      - 5432:5432
    env_file: .postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev
volumes:
  postgres-data:
    name: postgres-data
    driver: local
networks:
  dev:
    name: dev
