version: '3.8'
name: production
services:
  eu-tours-prod:
    container_name: eu-tours-prod
    image: anicmarko9/eu-tours-prod:1.0
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - prod
    ports:
      - '80:80'
    env_file: .env
networks:
  prod:
    name: prod
